#!/bin/sh
# Regenerate .agents/ubiquitous-language-index.md from the two vocabulary files.
#
# The index is a POINTER TABLE, never a summary: it carries no definitions, so it cannot
# disagree with the body it points at (ADR-0041). That is the same "lossless, never a digest"
# discipline as the corpus pack (ADR-0024), adapted to a file that has to persist — `@` imports
# a path and cannot run a script, so the index is checked in and verify-scaffold.sh §11 diffs it
# against a fresh build to catch staleness.
#
# Usage:  sh .agents/scripts/build-glossary-index.sh [output-path]
#
# Exit codes:
#   0  index written
#   3  a source file is missing

set -eu

PROJECT_ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$PROJECT_ROOT"

_body='.agents/ubiquitous-language.md'
_scaffold='.agents/ubiquitous-language-scaffold.md'
_out=${1:-.agents/ubiquitous-language-index.md}

for _src in "$_body" "$_scaffold"; do
  if [ ! -f "$_src" ]; then
    echo "build-glossary-index: missing source $_src" >&2
    exit 3
  fi
done

# Emit "### <section>" then one ' · '-joined line of terms, for every `##` section holding a
# vocabulary table. A table is indexed only once its `| Term |` header has been seen, so any
# other table in these files (the body's own "The five files" map, for one) is ignored rather
# than having its first column mistaken for vocabulary. Column 2 of each row is the term.
#
# A term is listed once per section. Some terms legitimately hold more than one row — a concept
# defined once for the Rust side and once for the TypeScript side, say — and where both rows sit
# in the same section the second adds no pointer, only noise. Across sections the repeat is kept:
# two sections means two places to read, which is exactly what a pointer table is for.
_terms() {
  awk '
    /^## / { section = substr($0, 4); active = 0; next }
    /^\| / {
      if ($0 ~ /^\|[-: |]+\|$/) next
      term = $2
      sub(/^[ \t]+/, "", term); sub(/[ \t]+$/, "", term)
      if (term == "Term") { active = 1; next }
      if (!active || section == "") next
      if ((section SUBSEP term) in listed) next
      listed[section SUBSEP term] = 1
      if (section in seen) { list[section] = list[section] " · " term }
      else { seen[section] = 1; order[++n] = section; list[section] = term }
    }
    END { for (i = 1; i <= n; i++) printf "### %s\n%s\n\n", order[i], list[order[i]] }
  ' FS='|' "$1"
}

{
  printf '# Ubiquitous Language — Index\n\n'
  printf '> Generated by `.agents/scripts/build-glossary-index.sh` — do not edit by hand.\n'
  printf '> A pointer table, never a summary: it carries no definitions, so it cannot disagree\n'
  printf '> with the body. Read the named file for the definition.\n'
  printf '>\n'
  printf '> Invariants are not indexed — they are `@`-imported in full\n'
  printf '> (`.agents/ubiquitous-language-invariants.md`, and 39–56 in the scaffold file).\n'
  printf '>\n'
  printf '> No `Last updated` here: this file is derived, so a date would be one more thing that\n'
  printf '> can disagree with the body. Freshness is checked by rebuilding it (verify-scaffold.sh 11d).\n\n'
  printf '## %s\n\n' "$_body"
  _terms "$_body"
  printf '## %s\n\n' "$_scaffold"
  _terms "$_scaffold"
} > "$_out"

echo "build-glossary-index: wrote $_out"
